// express_backend/react-client/src/components/postcomponents/SinglePost.js
import React, { Component } from "react";
import { Link } from "react-router-dom";
import utils from "../../utils/utils";
import axios from "axios";
import MenuBar from "../layout/MenuBar";

export default class SinglePost extends Component {
  constructor(props) {
    super(props);
    this.proxyurl = `${utils.proxyurl_api}/posts`;
    this.state = {
      title: "",
      author: "",
      category: "",
      posttext: ""
    };
  }
  componentDidMount() {
    this.getPostById();
  }
  getPostById = () => {
    axios
      .get(this.proxyurl + "/" + this.props.match.params.id)
      .then(res => {
        console.log("headers: " + JSON.stringify(res.headers));
        this.setState(res.data);
      })
      .catch(err => console.log("HOMEY ERROR: " + err));
  };
  render() {
    return (
      <div className="container">
        <MenuBar />
        <div className="border jumbotron text-center mb-0">
          <h1>Single Post View</h1>
        </div>
        <div className="border card">
          <h3 className="card-title text-center">{this.state.title}</h3>
          <div className="card-body">
            <p className="card-text">
              <span>
                by: {this.state.author} on {this.state.date}
              </span>
              <br />
              <span>category: {this.state.category}</span>
              <br />
              <span>{this.state.posttext}</span>
            </p>
          </div>
        </div>
      </div>
    );
  }
}

// express_backend/vue_frontend/src/components/posts/SinglePost.vue
<template>
  <div class="container">
    <div class="jumbotron text-center mb-1 border border-primary">
      <h1>Single Post View</h1>
      <p class="text-muted">(Click on post title to return to post index)</p>
    </div>
    <div class="card bg-light text-dark">
      <div class="card-body">
        <router-link to="/posts">
          <h2 class="card-title">{{post.title}}</h2>
        </router-link>
        <p class="card-text font-weight-light">
          <span>
            <i>author:</i>
            {{post.author}}
          </span>
          <br />
          <span>
            <i>entered on:</i>
            {{post.date}}
          </span>
          <br />
          <span>
            <i>category:</i>
            {{post.category}}
          </span>
        </p>
        <hr />
        <editor
          :api-key="this.getTinyConfig.api_key"
          v-bind:initial-value="post.posttext"
          :init="this.getTinyConfig"
        ></editor>
      </div>
    </div>
    <button v-on:click="gotoEditPost" class="btn btn-primary">Edit</button>
    <button v-on:click="gotoDeletePost" class="btn btn-danger">Delete</button>
  </div>
</template>

<script>
import { mapGetters } from "vuex";
import Editor from "@tinymce/tinymce-vue";
export default {
  name: "SinglePost",
  components: {
    editor: Editor
  },
  props: ["id"],
  computed: {
    ...mapGetters(["getProxy", "getPostsProxyStubs", "getTinyConfig"]),
    postByIdEndpoint() {
      return `${this.getProxy}${this.getPostsProxyStubs.getpostsroute}/${this.id}`;
    }
  },
  methods: {
    gotoEditPost() {
      this.$router.push(`/editpost/${this.id}`);
    },
    gotoDeletePost() {
      this.$router.push(`/deletepost/${this.id}`);
    },
    getPostById() {
      fetch(this.postByIdEndpoint, {
        method: "GET",
        headers: {
          "Content-Type": "application/json"
        }
      })
        .then(res => res.json())
        .then(doc => {
          this.post = { ...doc };
        })
        .catch(err => {
          this.post = {
            _id: "2",
            title: "Single Error post",
            author: "none",
            date: "none",
            category: "error",
            posttext: err
          };
        });
    }
  },
  created() {
    this.getPostById();
  },
  data() {
    return {
      post: {}
    };
  }
};
</script>

<style scoped>
.post-image {
  max-width: 60%;
  width: auto;
  margin-right: 5px;
  border-radius: 5px;
  border: 3px solid rgba(0, 0, 0, 0.7);
  float: left;
}
</style>
