// vue_frontend/src/components/posts/DeletePost.vue
<template>
  <div class="container">
    <div class="jumbotron text-center">
      <h1>Are You Sure?</h1>
      <button v-on:click="yesImSure" class="btn btn-danger m-1">Yes, Blow It Away</button>
      <button v-on:click="noImNotSure" class="btn btn-primary m-1">No, Go Back To Posts List</button>
    </div>
  </div>
</template>
<script>
import { mapGetters } from "vuex";
import axios from "axios";

export default {
  name: "DeletePost",
  props: ["id"],
  computed: {
    ...mapGetters(["getProxy", "getPostsProxyStubs", "getCredentials"]),
    deletePostByIdEndpoint() {
      return `${this.getProxy}${this.getPostsProxyStubs.deletepostroute}/${this.id}`;
    },
    bearerToken() {
      return `Bearer ${this.getCredentials.accessToken}`;
    }
  },
  methods: {
    noImNotSure() {
      this.$router.push("/posts");
    },
    yesImSure() {
      axios
        .delete(this.deletePostByIdEndpoint, {
          headers: { authorization: this.bearerToken }
        })
        .then(() => {
          this.$router.push("/posts");
        })
        .catch(err => {
          this.$router.push(`/newpostfailed/${err.message}`);
        });
    }
  },
  beforeRouteEnter(to, from, next) {
    next(vm => {
      if (!vm.$store.getters.isLoggedIn) {
        next("/login");
      } else {
        next();
      }
    });
  }
};
</script>
<style scoped>
</style>

// express_backend/react-client/src/components/postcomponents/DeletePost.js
import React, { Component } from "react";
import axios from "axios";
import { Link } from "react-router-dom";
import utils from "../../utils/utils";

export default class DeletePost extends Component {
  constructor(props) {
    super(props);
    this.proxyurl = `${utils.proxyurl_api}/posts`;
  }
  yesImSure = () => {
    const auth_token = utils.getTokenFromLocal();
    axios
      .delete(this.proxyurl + "/delete/" + this.props.match.params.id, {
        headers: { authorization: `Bearer ${auth_token.token}` }
      })
      .then(res => {
        console.log("deleted post :" + res);
        this.props.history.push("/delconfirmed");
      })
      .catch(err => console.log("HOMEY ERROR: " + err));
  };
  render() {
    return (
      <div className="container">
        <div className="jumbotron text-center">
          <h3>Are you sure?</h3>
          <div className="button-group">
            <button className="btn btn-danger mr-1" onClick={this.yesImSure}>
              Yes
            </button>
            <Link to="/" className="btn btn-primary">
              Cancel
            </Link>
          </div>
        </div>
      </div>
    );
  }
}
