// vue_frontend/src/components/posts/SinglePost.vue
<template>
  <div class="container">
    <div class="card bg-light text-dark">
      <div class="card-body">
        <router-link to="/posts">
          <h2 class="card-title">{{post.title}}</h2>
        </router-link>
        <p class="card-text">
          <span>author: {{post.author}}</span>
          <br />
          <span>category: {{post.category}}</span>
        </p>
        <hr />
        <p>{{post.posttext}}</p>
      </div>
    </div>
    <button class="btn btn-primary">Edit</button>
    <button class="btn btn-danger">Delete</button>
  </div>
</template>

<script>
import { mapGetters } from "vuex";
import axios from "axios";

export default {
  name: "SinglePost",
  props: ["id"],
  computed: {
    ...mapGetters(["getProxy","getPostsProxyStubs"])
  },
  methods: {
    getPostById() {
      console.log(`${this.getProxy}${this.getPostsProxyStubs.getpostsroute}/${this.id}`)
      axios
        .get(`${this.getProxy}${this.getPostsProxyStubs.getpostsroute}/${this.id}`)
        .then(doc => {
          this.post = { ...doc.data };
        })
        .catch(err => {
          this.post = {
            _id: "2",
            title: "Single Error post",
            author: "none",
            date: "none",
            category: "error",
            posttext: err
          };
        });
    }
  },
  created() {
    this.getPostById();
  },
  data() {
    return {
      post: {}
    };
  }
};
</script>

<style scoped>
</style>

// express_backend/react-client/src/components/postcomponents/SinglePost.js
import React, { Component } from "react";
import { Link } from "react-router-dom";
import utils from "../../utils/utils";
import axios from "axios";
import MenuBar from "../layout/MenuBar";

export default class SinglePost extends Component {
  constructor(props) {
    super(props);
    this.proxyurl = `${utils.proxyurl_api}/posts`;
    this.state = {
      title: "",
      author: "",
      category: "",
      posttext: ""
    };
  }
  componentDidMount() {
    this.getPostById();
  }
  getPostById = () => {
    axios
      .get(this.proxyurl + "/" + this.props.match.params.id)
      .then(res => {
        console.log("headers: " + JSON.stringify(res.headers));
        this.setState(res.data);
      })
      .catch(err => console.log("HOMEY ERROR: " + err));
  };
  render() {
    return (
      <div className="container">
        <MenuBar />
        <div className="border jumbotron text-center mb-0">
          <h1>Single Post View</h1>
        </div>
        <div className="border card">
          <h3 className="card-title text-center">{this.state.title}</h3>
          <div className="card-body">
            <p className="card-text">
              <span>
                by: {this.state.author} on {this.state.date}
              </span>
              <br />
              <span>category: {this.state.category}</span>
              <br />
              <span>{this.state.posttext}</span>
            </p>
          </div>
        </div>
      </div>
    );
  }
}
