// express_backend/react-client/src/components/postcomponents/EditPost.js
import React, { Component } from "react";
import { Link } from "react-router-dom";
import axios from "axios";
import utils from "../../utils/utils";

export default class EditPost extends Component {
  constructor(props) {
    super(props);
    this.proxyurl = `${utils.proxyurl_api}/posts`;
    this.state = {
      title: "",
      author: "",
      category: "",
      posttext: ""
    };
  }
  componentDidMount() {
    this.getPostById();
  }
  getPostById = () => {
    axios
      .get(this.proxyurl + "/" + this.props.match.params.id)
      .then(res => {
        console.log("headers: " + JSON.stringify(res.headers));
        this.setState(res.data);
      })
      .catch(err => console.log("HOMEY ERROR: " + err));
  };

  updatePost = () => {
    const updated = {
      title: this.state.title,
      author: this.state.author,
      category: this.state.category,
      posttext: this.state.posttext
    };
    const auth_token = utils.getTokenFromLocal();
    if (auth_token.loggedin) {
      axios
        .patch(this.proxyurl + "/edit/" + this.props.match.params.id, updated, {
          headers: { authorization: `Bearer ${auth_token.token}` }
        })
        .then(res => console.log("post updated. status: " + res))
        .catch(err => console.log("HOMEY UPDATE ERROR: " + err));
    }
  };
  handleTitle = event => {
    this.setState({ title: event.target.value });
  };
  handleAuthor = event => {
    this.setState({ author: event.target.value });
  };
  handleCategory = event => {
    this.setState({
      category: event.target.value
    });
  };
  handlePosttext = event => {
    this.setState({ posttext: event.target.value });
  };
  handleSubmit = event => {
    event.preventDefault();
    console.log("submitting this post: " + JSON.stringify(this.state));
    this.updatePost();
    this.props.history.push("/editconfirmed");
  };
  render() {
    return (
      <div className="container">
        <div className="jumbotron text-center mb-1">
          <h2>Edit post</h2>
        </div>
        <form onSubmit={this.handleSubmit}>
          <div className="form-group">
            <label>Title:</label>
            <input
              type="text"
              className="form-control"
              value={this.state.title}
              onChange={this.handleTitle}
            />
          </div>
          <div className="form-group">
            <label>Author:</label>
            <input
              type="text"
              className="form-control"
              value={this.state.author}
              onChange={this.handleAuthor}
            />
          </div>
          <div className="form-group">
            <label>Category:</label>
            <input
              type="text"
              className="form-control"
              value={this.state.category}
              onChange={this.handleCategory}
            />
          </div>
          <div className="form-group">
            <label>Post Text:</label>
            <textarea
              className="form-control"
              value={this.state.posttext}
              onChange={this.handlePosttext}
            />
          </div>
          <div className="form-group">
            <input
              type="submit"
              className="btn btn-primary mr-1"
              value="Update Post"
            />
            <Link to="/" className="btn btn-secondary">
              Cancel
            </Link>
          </div>
        </form>
      </div>
    );
  }
}

// vue_frontend/src/components/posts/EditPost.vue
<template>
  <div class="container">
    <form v-on:submit.prevent="editPostById">
      <div class="form-group">
        <label>Title:</label>
        <input v-model="post.title" type="text" class="form-control" />
      </div>
      <div class="form-group">
        <label>Author:</label>
        <input v-model="post.author" type="text" class="form-control" />
      </div>
      <div class="form-group">
        <label>Category:</label>
        <input v-model="post.category" type="text" class="form-control" />
      </div>
      <div class="form-group">
        <label>Post text:</label>
        <textarea v-model="post.posttext" type="text" class="form-control" />
      </div>
      <button type="submit" class="btn btn-primary">Submit Post</button>
    </form>
  </div>
</template>
<script>
import { mapGetters } from "vuex";


export default {
  name: "EditPost",
  props: ["id"],
  computed: {
    ...mapGetters(["getProxy", "getPostsProxyStubs", "getCredentials"]),
    getPostByIdEndpoint() {
      return `${this.getProxy}${this.getPostsProxyStubs.getpostsroute}/${this.id}`;
    },
    editPostByIdEndpoint() {
      return `${this.getProxy}${this.getPostsProxyStubs.editpostroute}/${this.id}`;
    },
    bearerToken() {
      return `Bearer ${this.getCredentials.accessToken}`;
    }
  },
  methods: {
    editPostById() {
      fetch(this.editPostByIdEndpoint, {
        method: "PATCH",
        body: JSON.stringify(this.post),
        headers: {
          "Content-Type": "application/json",
          authorization: this.bearerToken
        }
      })
        .then(res => res.json())
        .then(() => {
          this.$router.push("/posts");
        })
        .catch(err => {
          this.$router.push(`/newpostfailed/${err.message}`);
        });
    },
    getPostById() {
      fetch(this.getPostByIdEndpoint, {
        method: "GET",
        headers: {
          "Content-Type": "application/json"
        }
      })
        .then(res => res.json())
        .then(doc => {
          this.post = { ...doc };
        })
        .catch(err => {
          this.post = {
            _id: "2",
            title: "Single Error post",
            author: "none",
            date: "none",
            category: "error",
            posttext: err
          };
        });
    }
  },
  created() {
    this.getPostById();
  },
  data() {
    return {
      post: {}
    };
  },
  beforeRouteEnter(to, from, next) {
    next(vm => {
      if (!vm.$store.getters.isLoggedIn) {
        next("/login");
      } else {
        next();
      }
    });
  }
};
</script>
<style scoped>
</style>
