// src/components/users/LoginFailed.vue
<template>
  <div class="container">
    <div class="jumbotron text-center">
      <h2>Login failed: {{message}}</h2>
      <router-link to="/login">Back to Login</router-link>
    </div>
  </div>
</template>
<script>
export default {
  name: "LoginFailed",
  props: ["message"]
};
</script>
<style scoped>
</style>

// express_backend/react-client/src/components/usercomponents/LoginFailed.js
import React from "react";
import { Link } from "react-router-dom";

export default function LoginFailed() {
  return (
    <div className="container">
      <div className="jumbotron text-center">
        <h3>Login failed</h3>
        <Link to="/login" className="btn btn-primary m-1">
          Back To Login
        </Link>
      </div>
    </div>
  );
}
