// express_backend/vue_frontend/src/components/users/UserLogin.vue
<template>
  <div class="container">
    <div class="jumbotron text-center border border-primary">
      <h2>User Login Page</h2>
      <router-link to="/adduser">
        <h5>Don't have an account?</h5>
      </router-link>
    </div>
    <form class="dologin" @submit.prevent="dologin" novalidate="true">
      <div class="form-group">
        <label for="exampleInputEmail1">Username:</label>
        <input
          v-model="login.username"
          type="text"
          class="form-control"
          id="exampleInputEmail1"
          aria-describedby="emailHelp"
          placeholder
        />
        <b v-if="this.formerrors.nousername">{{this.formerrors.nousername}}</b>
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">Password:</label>
        <input
          v-model="login.password"
          type="password"
          class="form-control"
          id="exampleInputPassword1"
          placeholder
        />
        <b v-if="this.formerrors.nopassword">{{this.formerrors.nopassword}}</b>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</template>

<script>
export default {
  name: "UserLogin",
  computed: {},
  methods: {
    checkForm() {
      //
      // a variation on vue documentation cookbook at
      // https://vuejs.org/v2/cookbook/form-validation.html
      //

      if (
        this.login.username.length >= this.minlength &&
        this.login.password.length >= this.minlength
      ) {
        return true;
      }
      this.formerrors.nousername = null;
      this.formerrors.nopassword = null;
      if (this.login.username.length < this.minlength) {
        this.formerrors.nousername = `Username must be at least ${this.minlength} characters`;
      }
      if (this.login.password.length < this.minlength) {
        this.formerrors.nopassword = `Password must be at least ${this.minlength} characters`;
      }
      return false;
    },
    dologin() {
      if (this.checkForm()) {
        this.nowDoLogin();
      }
    },
    nowDoLogin() {
      this.$store
        .dispatch("doLogin", { ...this.login })
        .then(() => {
          this.$router.push("/posts");
        })
        .catch(err => {
          this.$router.push(`/loginfailed/${err.message}`);
        });
    }
  },
  data() {
    return {
      minlength: 4,
      formerrors: {
        nousername: null,
        nopassword: null
      },
      login: {
        username: "",
        password: ""
      }
    };
  }
};
</script>

<style scoped>
b {
  color: crimson;
}
</style>

// express_backend/react-client/src/components/usercomponents/UserLogin.js
import React, { Component } from "react";
import { Link } from "react-router-dom";
import axios from "axios";
import utils from "../../utils/utils";
export default class UserLogin extends Component {
  constructor(props) {
    super(props);
    this.proxyurl = `${utils.proxyurl_api}/users`;

    this.state = {
      username: "",
      password: ""
    };
  }
  loginUser = () => {
    const addstub = "/login";
    axios
      .post(`${this.proxyurl}${addstub}`, this.state)
      .then(res => {
        const auth_data = {
          username: this.state.username,
          token: res.data.token
        };
        utils.saveAuthInfoToLocal(auth_data);
        this.props.history.push("/");
      })
      .catch(err => {
        console.log(err);
        this.props.history.push("/loginfailed");
      });
  };
  handleUsername = event => {
    this.setState({ username: event.target.value });
  };
  handlePassword = event => {
    this.setState({ password: event.target.value });
  };
  handleSubmit = event => {
    event.preventDefault();
    this.loginUser();
  };
  render() {
    return (
      <div className="container">
        <div className="card">
          <div className="card-header">
            <h2 className="card-title text-center">Blog Application Login</h2>
            <Link to="/newuser">
              <h5 className="card-subtitle text-center mt-1">
                Don't have an account?
              </h5>
            </Link>
            <Link to="/">
              <h5 className="card-subtitle text-center text-muted mt-2">
                Back to blog
              </h5>
            </Link>
          </div>
          <div className="card-body">
            <form onSubmit={this.handleSubmit}>
              <div className="form-group">
                <label>Username:</label>
                <input
                  type="text"
                  className="form-control"
                  value={this.state.username}
                  onChange={this.handleUsername}
                />
                <label>Password:</label>
                <input
                  type="password"
                  className="form-control"
                  value={this.state.password}
                  onChange={this.handlePassword}
                />
                <input
                  type="submit"
                  className="btn btn-primary mt-2"
                  value="Submit User"
                />
              </div>
            </form>
          </div>
        </div>
      </div>
    );
  }
}
